---
- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present

- name: Start PostgreSQL service
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create application database
  postgresql_db:
    name: app_db
    state: present

- name: Create application user
  postgresql_user:
    db: app_db
    name: app_user
    password: secretpassword
    priv: ALL
    state: present
